#!/bin/bash
cat > ls_cwd_content
total 48
drwxrwxr-x 2 ezz ezz 4096 Aug  7 16:23 .
drwxr-xr-x 6 ezz ezz 4096 Aug  7 13:09 ..
-rwxrw-r-- 1 ezz ezz   32 Aug  7 13:12 0-hello_world
-rwxrw-r-- 1 ezz ezz   28 Aug  7 13:36 1-confused_smiley
-rwxrw-r-- 1 ezz ezz   28 Aug  7 13:53 2-hellofile
-rwxrw-r-- 1 ezz ezz   39 Aug  7 13:54 3-twofiles
-rwxrw-r-- 1 ezz ezz   29 Aug  7 13:23 4-lastlines
-rwxrw-r-- 1 ezz ezz   29 Aug  7 13:24 5-firstlines
-rw-r--r-- 1 ezz ezz   36 Aug  7 16:06 6-third_line
-rw-r--r-- 1 ezz ezz   12 Aug  7 16:22 8-cwd_state
-rw-rw-r-- 1 ezz ezz   18 Aug  7 13:09 README.md
-rw-r--r-- 1 ezz ezz  744 Aug  7 16:21 iacta
